[project]
name = "gold-price-data-pipeline"
version = "0.1.0"
description = ""
authors = [
    {name = "S4njuuu3291",email = "sanju329121@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4 (>=4.14.3,<5.0.0)",
    "pywhatkit (>=5.4,<6.0)",
    "dotenv (>=0.9.9,<0.10.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
